#!/usr/bin/env python3
"""instr_hints.txt -> build/instr_hints.i  --  per-field help for the instrument editor.

Like help.txt/makehelp.py: the hint text is data a human edits, validated at build time
(a too-wide line fails the build instead of clipping on hardware). The renderer keys the
current INSTR field to a hint and draws it (inverted, ">> "-prefixed) on the bottom row.

Sections map to the INSTR field layout in src/main.asm:
  [COMMON]  rows 0-1 shared by every type (INST selector, TYPE)
  [FM]      FM voice rows 2+   (voice_lbl: HLD VOL PAN TSP TBL TBS ALGO FB AMS FMS SWEEP)
  [FM.OP]   FM op-grid cols, SCREEN order: ML DT TL RS AR D1 D2 RR SL AM
            (keyed by cur_col = display column, not the i_op storage slot)
  [TONE]/[NOISE]  psg_off rows 2+   [WAVE] wave_off rows 2+   [KIT]/[PERC] rows 2+
Lines within a section are in on-screen field order; a blank line = no hint for that field.

Emits (vasm Motorola syntax, flat 68000 address space):
  hint_type_ptr:  dc.l <per-type row array> x6   (index = i_type: FM KIT WAVE TONE NOISE PERC)
  hint_op:        dc.l <op-column hint> x OPS     (index = cur_col)
  each row array: dc.l <hint or 0> x ROWS         (index = cur_row; 0 = no hint / blank)
"""
import sys

MAX_W = 35   # chars/line; the renderer adds a ">> " prefix -> <=38 on the 40-col plane
ROWS  = 16   # per-type row-array length (INSTR top rows never exceed ~12)
OPS   = 10   # FM operator-grid columns

# i_type order (src/main.asm i_type equ): 0 FM, 1 KIT, 2 WAVE, 3 TONE, 4 NOISE, 5 PERC
TYPE_ORDER = ['FM', 'KIT', 'WAVE', 'TONE', 'NOISE', 'PERC']


def die(m):
    sys.stderr.write("makehints: " + m + "\n")
    sys.exit(1)


def parse(text):
    sec, cur = {}, None
    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip()
        s = line.strip()
        if s.startswith('#'):
            continue
        if s.startswith('[') and s.endswith(']'):
            cur = s[1:-1].upper()
            sec.setdefault(cur, [])
            continue
        if cur is None:
            if s == '':
                continue
            die(f'line {n}: text before any [SECTION]')
        if '"' in line:
            die(f'line {n}: a double-quote breaks the emitted string literal')
        if len(line) > MAX_W:
            die(f'line {n}: {len(line)} chars > MAX_W {MAX_W} -- would clip: {line!r}')
        sec[cur].append(line)
    for k in sec:                               # drop leading/trailing blanks (e.g. the gap
        while sec[k] and sec[k][0] == '':        # before the next [SECTION]); keep internal
            sec[k].pop(0)                        # blanks -- those mean "this field has no hint"
        while sec[k] and sec[k][-1] == '':
            sec[k].pop()
    return sec


def emit(sec, path):
    strs = []                                   # (label, text) for non-blank hints

    def slot(text):
        if text.strip() == '':
            return '0'                          # blank -> no hint
        lbl = f'h_{len(strs)}'
        strs.append((lbl, text))
        return lbl

    common = sec.get('COMMON', [])
    L = ['; generated by tools/makehints.py from instr_hints.txt -- DO NOT EDIT', '    even']

    arrays = []                                 # (array_label, [slot ptrs])
    for t in TYPE_ORDER:
        rows = (common + sec.get(t, []))[:ROWS]
        ptrs = [slot(x) for x in rows] + ['0'] * (ROWS - len(rows))
        arrays.append((f'hint_rows_{t.lower()}', ptrs))

    ops = sec.get('FM.OP', [])[:OPS]
    opp = [slot(x) for x in ops] + ['0'] * (OPS - len(ops))

    L.append('hint_type_ptr:')                  # index = i_type
    L.append('    dc.l ' + ', '.join(a[0] for a in arrays))
    L.append('hint_op:')                        # index = cur_col
    L.append('    dc.l ' + ', '.join(opp))
    for lbl, ptrs in arrays:
        L.append(f'{lbl}:')
        L.append('    dc.l ' + ', '.join(ptrs))
    for lbl, text in strs:
        L.append(f'{lbl}: dc.b "{text}",0')
    L += ['    even', '']
    with open(path, 'w') as f:
        f.write('\n'.join(L))


def main():
    if len(sys.argv) != 3:
        die('usage: makehints.py instr_hints.txt build/instr_hints.i')
    sec = parse(open(sys.argv[1]).read())
    emit(sec, sys.argv[2])
    total = sum(len(v) for v in sec.values())
    print(f'makehints: {total} lines, {len(TYPE_ORDER)} types -> {sys.argv[2]}')


if __name__ == '__main__':
    main()
