#!/usr/bin/env python3
"""cmd_hints.txt -> build/cmd_hints.i  --  per-command help for the PHRASE/TABLE editors.

Sibling of makehints.py (INSTR field hints). The hint text is data a human edits,
validated at build time (a too-wide line fails the build instead of clipping on
hardware). The renderer keys the command byte under the cursor to a hint and draws it
(inverted, '>'-capped) on the bottom row -- shared bar renderer with the INSTR hints.

Input: one line per command letter A..Z, in order (<=26 lines); a blank line = no hint.

Emits (vasm Motorola syntax, flat 68000 address space):
  cmd_hint:  dc.l <hint or 0> x 27   (index = command value: 0 = none/'-', 1..26 = A..Z)
"""
import sys

MAX_W = 35   # chars/line; the renderer adds a '> ' prefix -> <=38 on the 40-col plane
NCMD  = 26   # command letters A..Z


def die(m):
    sys.stderr.write("makecmdhints: " + m + "\n")
    sys.exit(1)


def parse(text):
    rows = []
    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip()
        if line.lstrip().startswith('#'):
            continue
        if '"' in line:
            die(f'line {n}: a double-quote breaks the emitted string literal')
        if len(line) > MAX_W:
            die(f'line {n}: {len(line)} chars > MAX_W {MAX_W} -- would clip: {line!r}')
        rows.append(line)
    while rows and rows[0] == '':          # drop the leading blank(s) after the header comment
        rows.pop(0)
    while rows and rows[-1] == '':         # and any trailing blanks
        rows.pop()
    if len(rows) > NCMD:
        die(f'{len(rows)} command lines > {NCMD} (A..Z)')
    return rows


def emit(rows, path):
    strs = []                              # (label, text) for non-blank hints

    def slot(text):
        if text.strip() == '':
            return '0'                     # blank -> no hint
        lbl = f'ch_{len(strs)}'
        strs.append((lbl, text))
        return lbl

    ptrs = ['0']                           # index 0 = no command ('-')
    ptrs += [slot(x) for x in rows]
    ptrs += ['0'] * (1 + NCMD - len(ptrs)) # pad to 27 (0 + A..Z)

    L = ['; generated by tools/makecmdhints.py from cmd_hints.txt -- DO NOT EDIT', '    even']
    L.append('cmd_hint:')                  # index = command value 0..26
    L.append('    dc.l ' + ', '.join(ptrs))
    for lbl, text in strs:
        L.append(f'{lbl}: dc.b "{text}",0')
    L += ['    even', '']
    with open(path, 'w') as f:
        f.write('\n'.join(L))


def main():
    if len(sys.argv) != 3:
        die('usage: makecmdhints.py cmd_hints.txt build/cmd_hints.i')
    rows = parse(open(sys.argv[1]).read())
    emit(rows, sys.argv[2])
    print(f'makecmdhints: {len(rows)} commands -> {sys.argv[2]}')


if __name__ == '__main__':
    main()
