#!/usr/bin/env python3
"""help.txt -> build/help.i  --  the genmddj HELP screen, built from data not code.

The help text is a plain-text file a human edits; this turns it into an assembler
include the ROM renderer walks. A bad edit (over-wide line, over-tall page, a quote
char) FAILS THE BUILD instead of clipping silently on hardware -- that's the whole
point. Ported from sms_tracker/HELP.md; emits vasm Motorola syntax (dc.b/dc.l) for
genmddj's flat 68000 address space (the SMS version emits 16-bit WLA-DX .dw/.db).

Data model the renderer expects (see render_help in src/main.asm):
  HELP_PAGES equ N          ; page count
  help_pages: dc.l p0,...   ; long pointer table (flat 24-bit address space)
  help_pN:    a run of NUL-terminated screen lines, then a $FF page terminator
              $00 alone = a blank row ; $01,$00 = the @VERSION live-stamp marker
The renderer scans each line for ':' and inverts it (title highlight) if present.
"""
import sys

MAX_W    = 38   # chars/line: body draws from col 1 on the 40-col (H40) plane
MAX_ROWS = 20   # rows/page: body starts at screen row 8; the plane is 28 rows tall


def die(msg):
    sys.stderr.write("makehelp: " + msg + "\n")
    sys.exit(1)


def parse(text):
    pages = [[]]
    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip()                     # trailing space trimmed; leading kept
        if line.lstrip().startswith('#'):
            continue                            # comment
        if line.strip() == '---':
            pages.append([])                    # page break
            continue
        if '"' in line:
            die(f'line {n}: a double-quote breaks the emitted string literal')
        if len(line) > MAX_W:
            die(f'line {n}: {len(line)} chars > MAX_W {MAX_W} -- would clip: {line!r}')
        pages[-1].append(line)
    out = []
    for p in pages:                             # drop leading/trailing blank rows/page
        while p and p[0] == '':
            p.pop(0)
        while p and p[-1] == '':
            p.pop()
        if p:
            out.append(p)
    if not out:
        die('help.txt has no content')
    for i, p in enumerate(out):
        if len(p) > MAX_ROWS:
            die(f'page {i}: {len(p)} rows > MAX_ROWS {MAX_ROWS} -- would run off-screen')
    return out


def emit(pages, path):
    L = ['; generated by tools/makehelp.py from help.txt -- DO NOT EDIT',
         f'HELP_PAGES equ {len(pages)}',
         '    even',
         'help_pages:',
         '    dc.l ' + ', '.join(f'help_p{i}' for i in range(len(pages)))]
    for i, p in enumerate(pages):
        L.append(f'help_p{i}:')
        for line in p:
            if line == '':
                L.append('    dc.b 0')                   # blank row
            elif line == '@VERSION':
                L.append('    dc.b $01,0')               # live version + build stamp
            else:
                L.append(f'    dc.b "{line}",0')
        L.append('    dc.b $FF')                         # page terminator
    L += ['    even', '']
    with open(path, 'w') as f:
        f.write('\n'.join(L))


def main():
    if len(sys.argv) != 3:
        die('usage: makehelp.py help.txt build/help.i')
    with open(sys.argv[1]) as f:
        pages = parse(f.read())
    emit(pages, sys.argv[2])
    rows = sum(len(p) for p in pages)
    print(f'makehelp: {len(pages)} page(s), {rows} rows -> {sys.argv[2]}')


if __name__ == '__main__':
    main()
